### ISSUE TITLE
Question: A way to determine if the picker has been closed

### ISSUE THREAD

**Issue by jindrake** [Jose-cd/React-google-drive-picker#11]
Good day, Is there a way to detect if the user closed the picker (without selecting files)? Thanks

**Comment by Jose-cd** [comment]
Now you can pass a callback to the hook that will be excuted when the user closes the picker without selecting files.

`
const [openPicker, data, authResponse] = useDrivePicker({onCancel: () => console.log("User closed picker with close/cancel button")});  
`
