### ISSUE TITLE
Picker window does not open after signing in by an allowed user.

### ISSUE THREAD

**Issue by Jayraj-R** [Jose-cd/React-google-drive-picker#17]

**Comment by shafa909** [comment]
`{
   error: "idpiframe_initialization_failed"
   details:"You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."
}`

**Comment by shafa909** [comment]
need to migrate from the older Google Sign-In platform library to the newer Google Identity Services library for authentication

**Comment by Jose-cd** [comment]
I will work on the migration today.

**Comment by ggmartins091** [comment]
@Jose-cd any news on this? I'd be happy to help if you can share what you've done so far!

**Comment by gg-martins091** [comment]
> @Jose-cd any news on this? I'd be happy to help if you can share what you've done so far!

I've been able to get it to work on a local project, will open a PR tomorrow!

**Comment by Jose-cd** [comment]
> > @Jose-cd any news on this? I'd be happy to help if you can share what you've done so far!
> 
> I've been able to get it to work on a local project, will open a PR tomorrow!

I couldn't reproduce the error, so I would appreciate that PR! :D
