### ISSUE TITLE
Version 1.1.5 is broken.

### ISSUE THREAD

**Issue by ggmartins091** [Jose-cd/React-google-drive-picker#18]
I just realized that the 1.1.5 version does not have any files on the build.

If you install this package right now on the latest version the dist folder won't exist:
![Screenshot from 2022-05-17 18-30-13](https://user-images.githubusercontent.com/32683678/168913408-34fbb8ba-e97b-43ed-b364-863eaefba02a.png)

Going to version 1.1.4 works fine.

**Comment by Jose-cd** [comment]
Fixed, Thank you!
