### ISSUE TITLE
version 1.1.7 is empty . 1.1.6 is OK

### ISSUE THREAD

**Issue by shrikster** [Jose-cd/React-google-drive-picker#19]
when installing version 1.1.7 we get only these 3 files 
README.md     package.json  tsconfig.json

<img width="603" alt="image" src="https://user-images.githubusercontent.com/4500529/170711789-e673d79d-ccaa-4b2f-8e8b-bb54e7fc6eaa.png">

**Comment by Jose-cd** [comment]
fixed, thanks
