### ISSUE TITLE
403 error on opening the google drive picker

### ISSUE THREAD

**Issue by mohithworks** [Jose-cd/React-google-drive-picker#44]
![image](https://user-images.githubusercontent.com/111058159/228347104-b52489e8-08a0-466f-ab02-b7a6eaab67ad.png)
We are getting following error on opening the google-drive-picker. Please help us resolve this issue asap.

**Comment by emonno13** [comment]
@Jose-cd Hi Jose, how can you resolve this problem?

I followed this video ( https://www.youtube.com/watch?v=XjFzoAhf8D0 ) but the problem still happened
