### ISSUE TITLE
setOrigin is missing . It 's required if this picker is used in iframe.

### ISSUE THREAD

**Issue by tomvictor303** [Jose-cd/React-google-drive-picker#45]
Hello, hope you are doing well.

Now, I am developing Google Sheet add-on with React and Google Apps Script.
In UI, there is an option to select file from Google Drive.
For security issues, I used iframe and loaded UI from web app https://example.com.
This also saves much time for development.

In Google Sheet, the top host is https://docs.google.com
And picker is running at https://example.com.

_Incorrect origin value. Expected 'https://docs.google.com' but was 'http://example.com''_

https://developers.google.com/drive/picker/reference#picker-builder

I guess we should have setOrigin option.
Currently, I fixed this issue by hardcoding on node_modules.

But I am eager to use official npm module.
Looking forward to your kind consideration.

Best regards.

**Comment by egorkaru** [comment]
@tomvictor303 since #42 was merged, you can use `setOrigin` option. Just update `react-google-drive-picker ` to 1.2.1 version.
