### ISSUE TITLE
openPicker property 'supportDrives: false' displays shared drives.

### ISSUE THREAD

**Issue by R3GENERATion** [Jose-cd/React-google-drive-picker#58]
If I'm reading the documentation correctly, the sharedDrives property passed into openPicker (referring to example provided on npm) is supposed to toggle shared drives, with the default reading false. This property doesn't seem to have any effect on the outcome of the picker presented, specifying false continues to show files shared to your drive.

How are we getting around this? What should I be doing to this example to display only files owned by the user?

```js
import  { useEffect } from 'react';
import useDrivePicker from 'react-google-drive-picker'


function App() {
  const [openPicker, authResponse] = useDrivePicker();  
  // const customViewsArray = [new google.picker.DocsView()]; // custom view
  const handleOpenPicker = () => {
    openPicker({
      clientId: "xxxxxxxxxxxxxxxxx",
      developerKey: "xxxxxxxxxxxx",
      viewId: "DOCS",
      // token: token, // pass oauth token in case you already have one
      showUploadView: true,
      showUploadFolders: true,
      supportDrives: true,
      multiselect: true,
      // customViews: customViewsArray, // custom view
      callbackFunction: (data) => {
        if (data.action === 'cancel') {
          console.log('User clicked cancel/close button')
        }
        console.log(data)
      },
    })
  }


  
  return (
    <div>
        <button onClick={() => handleOpenPicker()}>Open Picker</button>
    </div>
  );
}

export default App;
```

**Comment by jay-cascade** [comment]
I am experiencing the same issue, setting the value to false or removing it still presents files outside of my drive!

@R3GENERATion , did you find a workaround?

**Comment by jay-cascade** [comment]
I found a [fork](https://github.com/TurboDocx/React-google-drive-picker) of this project which resolves my issue.

**Comment by R3GENERATion** [comment]
Thank you, the result was fine for my purposes. Thanks for sharing!
