### ISSUE TITLE
Ability to use different scopes and get auth token

### ISSUE THREAD

**Issue by paustint** [Jose-cd/React-google-drive-picker#6]
I would like the ability to get the authentication token obtained so that I can use it for subsequent API requests.

In addition, I would like to use different scopes, for example `https://www.googleapis.com/auth/drive.file`. It appears that the scope is hard-coded and unchangeable.

**Comment by Jose-cd** [comment]
Version 1.1.4 is now published, now you can add your own custom scopes and the hook returns the auth response like this

`const [openPicker, data, authResult] = useDrivePicker();`

authResult is an object with this type

`export type authResult = {
  access_token: string;
  
  authuser: string;
  client_id: string;
  cookie_policy: string;
  expires_at: string;
  expires_in: string;
  issued_at: string;
  login_hint: string;
  response_type: string | undefined;
  scope: string;
  session_state: null;
  status: { signed_in: boolean; method: string; google_logged_in: boolean };
  token_type: string;
  error: boolean | undefined;
};`

**Comment by Jose-cd** [comment]
Version 1.1.4 is now published, now you can add your own custom scopes and the hook returns the auth response like this

const [openPicker, data, authResult] = useDrivePicker();
